{
 "title": "Immeuble 1",
 "time": { "from": "2025-12-23T23:00:00.000Z", "to": "2025-12-30T22:59:59.000Z" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "max_data_time", "query": "SELECT MAX(time) from scores" }
  ]
 },
 "panels": [
  {
   "title": "Appartement 01 - Qualité de l'air - Semaine Dernière",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "sensor_scores",
     "rawSql": "SELECT iaq_2h, \"time\" FROM scores WHERE appart_id = 1"
    }
   ]
  },
  {
   "title": "Appartement 1 - Comparaison Hebdomadaire de l'IAQ sur le dernier mois",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "sensor_scores",
     "rawSql": "SELECT\r\n  \"time\" + interval '21 days' AS \"time\", \r\n  iaq_2h AS \"3 Semaines Avant\"\r\nFROM scores\r\nWHERE \"time\" BETWEEN \r\n    ($__timeTo()::timestamp - interval '28 days') \r\n    AND \r\n    ($__timeTo()::timestamp - interval '21 days')\r\n  AND appart_id = 1\r\nORDER BY 1"
    },
    {
     "dataset": "sensor_scores",
     "rawSql": "SELECT\r\n  \"time\" + interval '14 days' AS \"time\", \r\n  iaq_2h AS \"2 Semaines Avant\"\r\nFROM scores\r\nWHERE \"time\" BETWEEN \r\n    ($__timeTo()::timestamp - interval '21 days') \r\n    AND \r\n    ($__timeTo()::timestamp - interval '14 days')\r\n  AND appart_id = 1\r\nORDER BY 1"
    },
    {
     "dataset": "sensor_scores",
     "rawSql": "SELECT\r\n  \"time\" + interval '7 days' AS \"time\", \r\n  iaq_2h AS \"Semaine Dernière\"\r\nFROM scores\r\nWHERE \"time\" BETWEEN \r\n    ($__timeTo()::timestamp - interval '14 days') \r\n    AND \r\n    ($__timeTo()::timestamp - interval '7 days')\r\n  AND appart_id = 1\r\nORDER BY 1"
    },
    {
     "dataset": "sensor_scores",
     "rawSql": "SELECT\r\n  \"time\",\r\n  iaq_2h AS \"Cette Semaine\"\r\nFROM scores\r\nWHERE \"time\" BETWEEN ($__timeTo()::timestamp - interval '7 days') AND $__timeTo()\r\n  AND appart_id = 1\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Appartement 1 - Indice Isolation Thermique - Semaine Dernière",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "sensor_scores",
     "rawSql": "SELECT iit_2h, \"time\" FROM scores WHERE appart_id =1"
    }
   ]
  },
  {
   "title": "Appartement 1 - Evolution Hebdomadaire de l'IIT sur le dernier mois",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "sensor_scores",
     "rawSql": "SELECT\r\n  \"time\" + interval '21 days' AS \"time\", \r\n  iit_2h AS \"3 Semaines Avant\"\r\nFROM scores\r\nWHERE \"time\" BETWEEN \r\n    ($__timeTo()::timestamp - interval '28 days') \r\n    AND \r\n    ($__timeTo()::timestamp - interval '21 days')\r\n  AND appart_id = 1\r\nORDER BY 1"
    },
    {
     "dataset": "sensor_scores",
     "rawSql": "SELECT\r\n  \"time\" + interval '14 days' AS \"time\", \r\n  iit_2h AS \"2 Semaines Avant\"\r\nFROM scores\r\nWHERE \"time\" BETWEEN \r\n    ($__timeTo()::timestamp - interval '21 days') \r\n    AND \r\n    ($__timeTo()::timestamp - interval '14 days')\r\n  AND appart_id = 1\r\nORDER BY 1"
    },
    {
     "dataset": "sensor_scores",
     "rawSql": "SELECT\r\n  \"time\" + interval '7 days' AS \"time\", \r\n  iit_2h AS \"Semaine Dernière\"\r\nFROM scores\r\nWHERE \"time\" BETWEEN \r\n    ($__timeTo()::timestamp - interval '14 days') \r\n    AND \r\n    ($__timeTo()::timestamp - interval '7 days')\r\n  AND appart_id = 1\r\nORDER BY 1"
    },
    {
     "dataset": "sensor_scores",
     "rawSql": "SELECT\r\n  \"time\",\r\n  iit_2h AS \"Cette Semaine\"\r\nFROM scores\r\nWHERE \"time\" BETWEEN ($__timeTo()::timestamp - interval '7 days') AND $__timeTo()\r\n  AND appart_id = 1\r\nORDER BY 1"
    }
   ]
  }
 ]
}